#version 430

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(r16f, binding = 0) uniform image3D u_Out;
layout(binding = 1) uniform sampler3D u_In;

uniform ivec3 u_Size;
uniform float u_Dissipation;

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID.xyz);
    if (any(greaterThanEqual(id, u_Size))) {
        return;
    }

    vec3 uv = (vec3(id) + 0.5) / vec3(u_Size);
    float d = texture(u_In, uv).r;
    imageStore(u_Out, id, vec4(d * u_Dissipation));
}
